# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HelloCGI
                                 A QGIS plugin
 First plugin for demo assignment
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-02
        copyright            : (C) 2024 by Gul
        email                : gul.rajput.official@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HelloCGI class from file HelloCGI.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hello_cgi import HelloCGI
    return HelloCGI(iface)
